#!/bin/bash

. /etc/rc.d/functions

PIDFILE=/run/dhclient6.pid
PID=$(cat $PIDFILE 2>/dev/null)
if ! readlink -q /proc/$PID/exe | grep -q '^/usr/sbin/dhclient'; then
	PID=
	rm $PIDFILE 2>/dev/null
fi

case "$1" in
	start)
		stat_busy 'Starting dhclient'
		[ -z $PID ] && /usr/sbin/dhclient -6 eth0
		if [ $? != 0 ]; then
			stat_fail
		else
			add_daemon dhclient
			stat_done
		fi
		;;
	stop)
		stat_busy 'Stopping dhclient'
		[ ! -z $PID ] && /usr/sbin/dhclient -r -6 eth0 && /usr/sbin/ip link set dev eth0 down
		if [ $? != 0 ]; then
			stat_fail
		else
			rm_daemon dhclient
			stat_done
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" ;;
esac

