#!/bin/sh

set -e
set -o pipefail
set -u

if [ -n "$*" ];then
	echo "Running $0"
	sudo bash -s $1 <<'EOF'

	set -e
	set -o pipefail
	set -u

	switch=br0

	if [ ! -e /proc/net/dev_snmp6/$switch ]; then
		/usr/sbin/brctl addbr $switch
	fi
        /usr/sbin/ip link set $1 up
       	sleep 0.5s
	/usr/sbin/brctl show $switch | grep -q $1 || /usr/sbin/brctl addif $switch $1
EOF
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi

