#!/bin/sh
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
xautolock -time 10 -locker "i3lock -c 000000" &
if [ -z "${NXSESSIONID:-}" ]; then
	exec i3 -c ~/.i3/i3.conf
else
	exec i3 -c ~/.i3/i3-nx.conf
fi
