#!/bin/sh
xautolock -time 10 -locker "i3lock -c 000000 -i ~/.i3/i3lock.png" &
ibus-daemon drx &
[ -e ~/.fehbg ] && . ~/.fehbg
if [ -z "${NXSESSIONID:-}" ]; then
	xrandr --output DVI-1 --pos 1280x0
	exec i3 -c ~/.i3/i3.conf
else
	xrdb ~/.Xdefaults
	exec i3 -c ~/.i3/i3-nx.conf
fi
